allowBuilds:
  better-sqlite3: true
  exifreader: true
  gdal-async: true
  protobufjs: true
ignoredBuiltDependencies:
  - protobufjs
minimumReleaseAgeExclude:
  - exifreader@4.40.5
onlyBuiltDependencies:
  - better-sqlite3
  - exifreader
  - gdal-async
  - sharp
