allowBuilds:
  better-sqlite3: true
  exifreader: true
  gdal-async: true
  protobufjs: true
ignoredBuiltDependencies:
  - protobufjs
minimumReleaseAgeExclude:
  - '@dotenvx/dotenvx@2.14.0'
  - '@dotenvx/primitives@2.1.0'
onlyBuiltDependencies:
  - better-sqlite3
  - exifreader
  - gdal-async
  - sharp
